# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Tests unitaires de la couche logique

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore SushiGo/Logic_Test/Logic_Test.csproj
    - name: Build
      run: dotnet build SushiGo/Logic_Test/Logic_Test.csproj --no-restore
    - name: Test
      run: dotnet test SushiGo/Logic_Test/Logic_Test.csproj --no-build --verbosity normal
