name: Run Unit Tests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'

      - name: Restore dependencies
        run: dotnet restore Sushigo/**/*Test.csproj

      - name: Build and run tests
        run: dotnet test Sushigo/**/*Test.csproj --no-restore
